services:
  n8n:
    # IMAGEM ANTIGA (REMOVA OU COMENTE ESTA LINHA):
    # image: n8nio/n8n:1.111.0
    
    # NOVA INSTRUÇÃO (ADICIONE ESTA LINHA):
    build: .
    
    # ... (o resto da sua configuração continua igual)
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - DB_TYPE=postgresdb
